import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import NavigationProgressBar from "@/components/ui-components/navigation-progress-bar";
import NewIdeaModal from "@/components/dashboard/modals/new-post-modal";
import ShowInterestModal from "@/components/dashboard/modals/show-interest-modal";
import ThemeProvider from "@/components/ui-components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <NavigationProgressBar />
          <NewIdeaModal />
          <ShowInterestModal />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
