import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationProgressBar from "@/components/ui-components/navigation-progress-bar";
import NewIdeaModal from "@/components/dashboard/modals/new-post-modal";
import ShowInterestModal from "@/components/dashboard/modals/show-interest-modal";
import ThemeProvider from "@/components/ui-components/theme-provider";
import QueryProvider from "@/components/layer/QueryProvider";
import { Toaster } from "sonner";
import AuthBootstrap from "@/components/layer/AuthBootstrap";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <ThemeProvider>
            <AuthBootstrap />
            <Toaster position="top-center" visibleToasts={1} richColors />
            <NavigationProgressBar />
            <NewIdeaModal />
            <ShowInterestModal />
            {children}
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
